name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  checks: write
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: SolaceDev/solace-public-workflows/.github/workflows/hatch_ci.yml@main
    with:
      min-python-version: "3.10"
      max-python-version: "3.13"
      whitesource_project_name: ${{ github.event.repository.name }}
      whitesource_product_name: "solaceai"
      whitesource_config_file: "wss-unified-agent.config"

    secrets:
      SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
      WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
      MANIFEST_AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_READ_ONLY_AWS_ACCESS_KEY_ID }}
      MANIFEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_READ_ONLY_AWS_SECRET_ACCESS_KEY }}
      MANIFEST_AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
